spring: 
   config: 
    activate : 
      on-profile: dev

user:
    id: 1
    name: "John Doe - Dev"
    email: "john.doe@example.com"
    role: "ADMIN"
    active: true  
---
spring: 
   config: 
    activate : 
      on-profile: release
user:
    id: 1
    name: "John Doe- Release"
    email: "john.doe@example.com"
    role: "ADMIN"
    active: true  


