spring:
  profiles: dev
  
user:
    id: 1
    name: "John Doe - Dev"
    email: "john.doe@example.com"
    role: "ADMIN"
    active: true  
---
spring:
  profiles: release
user:
    id: 1
    name: "John Doe- Release"
    email: "john.doe@example.com"
    role: "ADMIN"
    active: true  

